---
dependencies: []

galaxy_info:
  role_name: jupyter_role
  author: CrustyBarnacle
  description: "Install, setup/configure Jupyter Lab via pipx and poetry."

  # https://creativecommons.org/licenses/by/4.0/
  license: "license (CC-BY-4.0)"

  # Currently working from and tested ansible version(s)
  min_ansible_version: 2.10.8
  platforms:
    - name: Ubuntu
      versions:
      - all
      - 22.04

  galaxy_tags:
    - jupyter
    - jupyter_notebook
    - jupyter_lab
    - ssl
    - https
    - web
